[package]
name = "hyperdome-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperdome-core = { "path" = "../hyperdome-core" }
hyperdome-api = { "path" = "../hyperdome-api" }